export const POPULAR_INTERVIEWS = [
  {
    track: "Software Engineering",
    title: "Software Engineering",
    blurb: "APIs, JavaScript, and how you build real software in a job interview.",
    tag: "Programming",
    difficulty: "MEDIUM",
    icon: "</>",
  },
  {
    track: "Data Structures & Algorithms",
    title: "DSA Interview",
    blurb: "Arrays, trees, graphs, and problem-solving like a coding round.",
    tag: "Programming",
    difficulty: "HARD",
    icon: "{ }",
  },
  {
    track: "System Design",
    title: "System Design",
    blurb: "Design feeds, URL shorteners, and systems that scale.",
    tag: "Architecture",
    difficulty: "HARD",
    icon: "⬡",
  },
  {
    track: "Data Science",
    title: "Data Science",
    blurb: "ML basics, experiments, and how you explain data decisions.",
    tag: "Data",
    difficulty: "MEDIUM",
    icon: "◈",
  },
  {
    track: "Product & Business",
    title: "Product Interview",
    blurb: "Prioritization, metrics, and product sense questions.",
    tag: "Product",
    difficulty: "MEDIUM",
    icon: "▣",
  },
  {
    track: "Behavioral / HR",
    title: "HR & Behavioral",
    blurb: "Tell me about yourself, teamwork, and how you handle conflict.",
    tag: "HR",
    difficulty: "EASY",
    icon: "◉",
  },
] as const;
